### ISSUE TITLE
Design Recommendations ( Rammed earth, Recycled Materials from the site - boulders, concrete etc.)   )- The notes here don't seem to relate . Check all, seem to be many inconsistencies.

### ISSUE THREAD

**Issue by pjconrad** [edanweis/LCC#102]

**Comment by edanweis** [comment]
The conditional logic that determines what recommendations feature in the list was just a rough guess based on the toolkit. We should review these rules.

**Comment by edanweis** [comment]
By _notes_ you mean the recommendations themselves? And what kind of inconsistencies, @pjconrad ?

**Comment by pjconrad** [comment]
no, i don't mean the recommendations. i mean the notes that describe the
recommendations are off. I.E. the notes that describe the rammed earth are
coming from some other recommendation.

**Comment by edanweis** [comment]
@pjconrad I was using the toolkit pdf as a guide, which includes for example, the following text for rammed earth.

![image](https://user-images.githubusercontent.com/2130136/64426432-d9b93480-d0f1-11e9-968d-dad579b7e395.png)

**Comment by pjconrad** [comment]
Ok, I will review it closely today and get back to you with any text edits needed from my end.

**Comment by pjconrad** [comment]
@edanweis @CNimmo16 
Here are the issues remaining with the design suggestions:
1. The text is cut off from the top
2. The icon is showing solid green where it should be showing the green plant vector graphic
3. The proper design suggestions are not showing up as they should (Previously for example, if I selected pedestrian concrete paving, a number of better paving options would have shown up based on the color coding in the spreadsheet.) The only icon that is showing up now is "Add more trees, wetlands or shrubs"

![image](https://user-images.githubusercontent.com/46090868/64927280-929c0500-d7bd-11e9-9dd2-54bd6e54eb5d.png)

**Comment by edanweis** [comment]
I can confirm the text is cut off. It wasn't before? 
@CNimmo16 The solid green error is likely vue-svgicon library converting the SVGs or coloring them with attributes. Could also be the conversion from the original toolkit PDF. One solution is to change them to png, but lose the dynamic SVG attributes.

**Comment by CNimmo16** [comment]
@edanweis that's so weird, the only thing I've done is added a pt-8 class to the v-content container to try to force it to add padding on all browsers, somehow that's ended up doing the opposite in your case. Presumably this is some bug in vuetify. I guess I can try adding the padding directly with css. With the icons it's definitely an issue with the conversion from the pdf. I can't find that in the drive folder so presumably I don't have access to it.

**Comment by CNimmo16** [comment]
@pjconrad sorry about the design recommendations not showing up correctly, a change I made when implementing the co2 values on the input page inadvertently stopped the design suggestions updating correctly. This is fixed in latest staging site.

**Comment by pjconrad** [comment]
@cnimmo16 thanks for taking a look, but the recommendations still aren’t working correctly on your staging site. Do you need to push out the update?

**Comment by CNimmo16** [comment]
@pjconrad I should've mentioned that you'll need to update an element quantity to update the relevant design suggestions for the project. The application is set up so that design suggestions are only ever updated when an element is, this means that any staging projects edited since the bug I accidentally introduced with the co2 update will have their design suggestions out of date. Could you try changing the quantity of an element then checking design suggestions again. It's working for me with all the ones I've tested.

**Comment by CNimmo16** [comment]
For example changing the quantity of pedestrian concrete paving to any value over zero should trigger the design suggestions for it to show up.

**Comment by pjconrad** [comment]
@cnimmo16 Top text is no longer cut off. However proper design suggestions still not showing and icons still have problems.

**Comment by CNimmo16** [comment]
@pjconrad Could you confirm you've followed the steps above, and if so could you provide examples of design suggestions that aren't showing up? I've tried this on several elements in new and existing projects and it's working fine for me. The icons I'm unable to fix without access to the original pdf toolkit Edan mentioned. Could this be shared with me?

**Comment by pjconrad** [comment]
@CNimmo16 here is a link to the icon PDF and .ai files: https://drive.google.com/open?id=1lyfhqGjouTfRYxfsls_dhwaQdBrDUhMt 

I have to get back to you on the design recommendation issues.
